name: CI/CD Pipeline
on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    name: Build, Test & Publish
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore dependencies
        run: dotnet restore ./Source/Fitness.slnx

      - name: Build project
        run: dotnet build ./Source/Fitness.slnx --no-restore --configuration Release

      #- name: Run Tests
      #  run: dotnet test ./Source/Fitness.sln --no-build --verbosity normal --configuration Release

      - name: Publish App
        run: dotnet publish ./Source/Fitness/Fitness.csproj --no-build --configuration Release -o ./publish

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-artifact
          path: ./publish

  deploy:
    name: Deploy
    needs: build-and-test
    runs-on: self-hosted
    
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: app-artifact
          path: ./temp-deploy

      - name: Sync files to production folder
        run: |
          # rsync kopiert die Dateien effizient. 
          # WICHTIG: Achte darauf, dass deine appsettings.Production.json auf dem Server 
          # nicht durch das Deployment überschrieben wird, falls du dort Passwörter hast.
          sudo rsync -av --exclude='appsettings.Production.json' ./temp-deploy/ /var/www/fitness/
          sudo chown -R www-data:www-data /var/www/fitness/

      - name: Restart App Service
        run: sudo systemctl restart Fitness.service

      - name: Cleanup temporary files
        run: rm -rf ./temp-deploy